/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a observer.h:observer.cpp ../xml/observer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OBSERVER_H_1351627265
#define OBSERVER_H_1351627265

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.bluez.Observer
 */
class ObserverAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bluez.Observer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bluez.Observer\">\n"
"    <method name=\"ServiceReceived\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"address\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"ManufacturerReceived\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"address\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"cid\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"value\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ObserverAdaptor(QObject *parent);
    virtual ~ObserverAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void ManufacturerReceived(const QString &address, ushort cid, const QByteArray &value);
    void ServiceReceived(const QString &address, ushort uuid, const QByteArray &value);
Q_SIGNALS: // SIGNALS
};

#endif
